import { ProjectType, Project, ScheduledTask } from './types';

export const mockProjects: Project[] = [
  {
    id: '1',
    userId: '1',
    title: 'Kahve Kafe Sunumu',
    type: ProjectType.SLIDES,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'Bir kahve kafe için sunum oluştur',
    createdAt: new Date(),
  },
  {
    id: '2',
    userId: '1',
    title: 'Pazar Analizi Raporu',
    type: ProjectType.DOCUMENT,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'Q4 pazar analizi raporu',
    createdAt: new Date(),
  },
  {
    id: '3',
    userId: '1',
    title: 'Ürün Tanıtım Görseli',
    type: ProjectType.IMAGE,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'Modern ürün tanıtım görseli',
    createdAt: new Date(),
  },
  {
    id: '4',
    userId: '1',
    title: 'Bütçe Tablosu',
    type: ProjectType.SHEET,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'Aylık bütçe takip tablosu',
    createdAt: new Date(),
  },
  {
    id: '5',
    userId: '1',
    title: 'Landing Page',
    type: ProjectType.WEBSITE,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'SaaS ürün landing page',
    createdAt: new Date(),
  },
  {
    id: '6',
    userId: '1',
    title: 'Tutorial Videosu',
    type: ProjectType.VIDEO,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'Ürün kullanım tutorial',
    createdAt: new Date(),
  },
  {
    id: '7',
    userId: '1',
    title: 'Q2 Sunumu',
    type: ProjectType.SLIDES,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'İkinci çeyrek sunumu',
    createdAt: new Date(),
  },
  {
    id: '8',
    userId: '1',
    title: 'Blog Yazısı',
    type: ProjectType.DOCUMENT,
    outputUrl: null,
    thumbnailUrl: null,
    isPublic: true,
    prompt: 'AI trendleri blog yazısı',
    createdAt: new Date(),
  },
];

export const mockScheduledTasks: ScheduledTask[] = [
  {
    id: '1',
    userId: '1',
    name: 'Pazartesi Pazar Raporu',
    cron: '0 9 * * 1',
    module: ProjectType.DOCUMENT,
    prompt: 'Haftalık pazar analizi raporu oluştur',
    active: true,
    lastRun: new Date(Date.now() - 86400000),
    nextRun: new Date(Date.now() + 604800000),
    createdAt: new Date(),
  },
  {
    id: '2',
    userId: '1',
    name: 'Aylık Bütçe Kontrolü',
    cron: '0 10 1 * *',
    module: ProjectType.SHEET,
    prompt: 'Aylık bütçe durumunu özetle',
    active: true,
    lastRun: new Date(Date.now() - 2592000000),
    nextRun: new Date(Date.now() + 2592000000),
    createdAt: new Date(),
  },
];

export const mockSkills = [
  {
    id: 'genel-asistan',
    name: 'Genel Asistan',
    description: 'Çok adımlı görevleri yönetebilen genel çalışma alanı asistanı',
    module: ProjectType.DOCUMENT,
    tags: ['genel', 'asistan', 'çok adımlı'],
    systemPrompt: 'Sen genel amaçlı bir AI asistanısın. Kullanıcının tüm görevlerinde yardımcı ol.',
    defaultParams: {},
  },
  {
    id: 'profesyonel-belge',
    name: 'Profesyonel Belge Oluşturucu',
    description: 'Derin analiz ile profesyonel belgeler, raporlar ve makaleler oluşturur',
    module: ProjectType.DOCUMENT,
    tags: ['belge', 'rapor', 'profesyonel', 'makale'],
    systemPrompt: 'Profesyonel belgeler oluştur. Resmi dil kullan, yapılandırılmış format tercih et.',
    defaultParams: { style: 'professional', format: 'docx' },
  },
  {
    id: 'sunum-olusturucu',
    name: 'Sunum Oluşturucu',
    description: 'Anlatıları profesyonel slaytlara dönüştürür, PowerPoint ve HTML çıktı üretir',
    module: ProjectType.SLIDES,
    tags: ['sunum', 'slayt', 'ppt', 'powerpoint'],
    systemPrompt: 'Etkileyici sunumlar oluştur. Her slayt için başlık, madde işaretleri ve görsel önerisi ver.',
    defaultParams: { slideCount: 10, theme: 'modern' },
  },
  {
    id: 'veri-analizi',
    name: 'Veri Analizi ve Tablo',
    description: 'Ham veriyi düzenli tablolara ve analitik raporlara dönüştürür',
    module: ProjectType.SHEET,
    tags: ['tablo', 'veri', 'analiz', 'rapor', 'excel'],
    systemPrompt: 'Verileri analiz et ve düzenli tablolar oluştur. İstatistiksel özet ve grafik önerileri ekle.',
    defaultParams: { format: 'xlsx' },
  },
  {
    id: 'podcast-uretim',
    name: 'Podcast Üretici',
    description: 'Otomatik araştırma ve kayıt — tek tıkla podcast içeriği oluşturur',
    module: ProjectType.DOCUMENT,
    tags: ['podcast', 'ses', 'otomatik araştırma'],
    systemPrompt: 'Podcast bölümleri için senaryo ve konuşma metinleri oluştur. Doğal ve akıcı bir dil kullan.',
    defaultParams: { duration: '15dk', language: 'tr' },
  },
  {
    id: 'web-sitesi-olusturucu',
    name: 'Web Sitesi Oluşturucu',
    description: 'Doğal dil ile tam kapsamlı web siteleri oluşturur ve canlı ön izleme sunar',
    module: ProjectType.WEBSITE,
    tags: ['web sitesi', 'landing page', 'full-stack'],
    systemPrompt: 'Modern, responsive web siteleri oluştur. Tailwind CSS ve Next.js standartlarına uygun kod yaz.',
    defaultParams: { framework: 'nextjs', style: 'modern' },
  },
  {
    id: 'video-planlayici',
    name: 'Video Planlayıcı',
    description: 'Görselden videoya dönüşüm, storyboard ve montaj planlaması yapar',
    module: ProjectType.VIDEO,
    tags: ['video', 'storyboard', 'montaj', 'görselden videoya'],
    systemPrompt: 'Video storyboard ve senaryolar oluştur. Sahne açıklamaları, kamera açıları ve süre notları ekle.',
    defaultParams: { resolution: '1080p', format: 'mp4' },
  },
  {
    id: 'gorsel-olusturucu',
    name: 'Görsel Oluşturucu ve Düzenleyici',
    description: 'Metinden görsel oluşturma, referans tabanlı düzenleme ve iyileştirme',
    module: ProjectType.IMAGE,
    tags: ['görsel', 'tasarım', 'düzenleme', 'AI görsel'],
    systemPrompt: 'Yüksek kaliteli görseller oluştur. Detaylı açıklamalardan görsel promptları üret.',
    defaultParams: { ratio: '16:9', style: 'photorealistic' },
  },
  {
    id: 'kahve-kultur-poster',
    name: 'Kahve Kültürü Posteri',
    description: 'Kahve kültürü temasında sosyal medya afişi ve poster tasarımı',
    module: ProjectType.IMAGE,
    tags: ['kahve', 'poster', 'sosyal medya', 'tasarım'],
    systemPrompt: 'Kahve temalı poster ve sosyal medya görselleri oluştur. Sıcak tonlar ve vintage stil kullan.',
    defaultParams: { ratio: '4:5', style: 'editorial' },
  },
  {
    id: 'pazarlama-sunumu',
    name: 'Pazarlama Pitch Deck',
    description: 'Yatırımcı sunumu ve pazarlama stratejisi şablonu',
    module: ProjectType.SLIDES,
    tags: ['pazarlama', 'yatırımcı', 'sunum', 'pitch'],
    systemPrompt: 'Profesyonel yatırımcı sunumları oluştur. Problem-çözüm-pazar modeli kullan.',
    defaultParams: { slideCount: 12, theme: 'corporate' },
  },
  {
    id: 'seo-blog',
    name: 'SEO Blog Yazısı',
    description: 'SEO uyumlu, anahtar kelime optimize edilmiş blog yazıları',
    module: ProjectType.DOCUMENT,
    tags: ['seo', 'blog', 'içerik', 'anahtar kelime'],
    systemPrompt: 'SEO uyumlu blog yazıları oluştur. Başlık, meta açıklama, H2/H3 başlıkları ve iç bağlantı önerileri ekle.',
    defaultParams: { wordCount: 1500, tone: 'informative' },
  },
  {
    id: 'urun-tanitim-gorseli',
    name: 'Ürün Tanıtım Görseli',
    description: 'E-ticaret ve sosyal medya için ürün tanıtım görselleri',
    module: ProjectType.IMAGE,
    tags: ['e-ticaret', 'ürün', 'tanıtım', 'sosyal medya'],
    systemPrompt: 'Ürün tanıtım görselleri oluştur. Temiz arka plan, profesyonel aydınlatma ve marka uyumu.',
    defaultParams: { ratio: '1:1', style: 'commercial' },
  },
  {
    id: 'finansal-rapor',
    name: 'Finansal Rapor Oluşturucu',
    description: 'Çeyreklik ve yıllık finansal raporlar, grafikler ve tablolar',
    module: ProjectType.SHEET,
    tags: ['finans', 'rapor', 'grafik', 'bütçe'],
    systemPrompt: 'Finansal raporlar oluştur. Gelir-gider tabloları, nakit akış grafikleri ve KPI özetleri ekle.',
    defaultParams: { period: 'quarterly', currency: 'TRY' },
  },
  {
    id: 'egitim-sunumu',
    name: 'Eğitim Sunumu',
    description: 'Eğitim ve öğretim amaçlı interaktif sunum şablonları',
    module: ProjectType.SLIDES,
    tags: ['eğitim', 'öğretim', 'sunum', 'interaktif'],
    systemPrompt: 'Eğitim sunumları oluştur. Öğrenme hedefleri, sorular ve etkileşimli öğeler ekle.',
    defaultParams: { slideCount: 15, theme: 'educational' },
  },
  {
    id: 'sosyal-medya-icerik',
    name: 'Sosyal Medya İçerik Paketi',
    description: 'Instagram, Twitter, LinkedIn için içerik takvimi ve görseller',
    module: ProjectType.IMAGE,
    tags: ['sosyal medya', 'instagram', 'linkedin', 'içerik takvimi'],
    systemPrompt: 'Sosyal medya içerik paketi oluştur. Platforma uygun boyutlarda görseller ve caption metinleri üret.',
    defaultParams: { platforms: ['instagram', 'linkedin'], count: 7 },
  },
  {
    id: 'teknik-dokuman',
    name: 'Teknik Dokümantasyon',
    description: 'API dokümantasyonu, kullanıcı kılavuzu ve teknik spesifikasyon',
    module: ProjectType.DOCUMENT,
    tags: ['teknik', 'dokümantasyon', 'API', 'kılavuz'],
    systemPrompt: 'Teknik dokümantasyon oluştur. API endpoint tabloları, kod örnekleri ve kullanım kılavuzları ekle.',
    defaultParams: { format: 'markdown', includeCodeExamples: true },
  },
  {
    id: 'is-plani',
    name: 'İş Planı Oluşturucu',
    description: 'Kapsamlı iş planı, pazar analizi ve finansal projeksiyon',
    module: ProjectType.DOCUMENT,
    tags: ['iş planı', 'pazar analizi', 'finansal', 'girişim'],
    systemPrompt: 'Detaylı iş planı oluştur. Yönetici özeti, pazar analizi, rekabet avantajı ve finansal projeksiyon ekle.',
    defaultParams: { period: '3 yıl', currency: 'TRY' },
  },
  {
    id: 'restoran-menu',
    name: 'Restoran Menü Tasarımı',
    description: 'Restoran ve kafe için profesyonel menü kartı ve fiyat listesi',
    module: ProjectType.IMAGE,
    tags: ['restoran', 'menü', 'kafe', 'tasarım'],
    systemPrompt: 'Restoran menü tasarımları oluştur. Kategorilere ayrılmış menü, fiyat listesi ve görsel düzen.',
    defaultParams: { ratio: 'A4', style: 'elegant' },
  },
  {
    id: 'proje-yonetim-tablosu',
    name: 'Proje Yönetim Tablosu',
    description: 'Gantt şeması, görev takibi ve kaynak planlama tablosu',
    module: ProjectType.SHEET,
    tags: ['proje yönetimi', 'gantt', 'görev takibi', 'planlama'],
    systemPrompt: 'Proje yönetim tablosu oluştur. Görev listesi, sorumlular, deadline ve durum takibi ekle.',
    defaultParams: { view: 'gantt', includeTimeline: true },
  },
  {
    id: 'portfolio-web-sitesi',
    name: 'Portfolio Web Sitesi',
    description: 'Kişisel veya kurumsal portfolio sitesi şablonu',
    module: ProjectType.WEBSITE,
    tags: ['portfolio', 'kişisel', 'web sitesi', 'şablon'],
    systemPrompt: 'Modern portfolio web sitesi oluştur. Hakkında, projeler, beceriler ve iletişim bölümleri ekle.',
    defaultParams: { framework: 'nextjs', theme: 'minimal' },
  },
  {
    id: 'infografik-olusturucu',
    name: 'İnfografik Oluşturucu',
    description: 'Verileri görsel infografiklere dönüştürür',
    module: ProjectType.IMAGE,
    tags: ['infografik', 'veri görselleştirme', 'bilgi grafiği'],
    systemPrompt: 'Veri odaklı infografikler oluştur. İstatistikleri görsel grafikler ve ikonlarla sun.',
    defaultParams: { ratio: '9:16', style: 'infographic' },
  },
  {
    id: 'toplanti-notu',
    name: 'Toplantı Notu ve Özet',
    description: 'Toplantı tutanakları, karar listesi ve aksiyon maddeleri',
    module: ProjectType.DOCUMENT,
    tags: ['toplantı', 'not', 'tutanak', 'aksiyon'],
    systemPrompt: 'Toplantı tutanakları oluştur. Katılımcılar, gündem, kararlar ve aksiyon maddeleri listele.',
    defaultParams: { format: 'structured', includeActionItems: true },
  },
  {
    id: 'e-ticaret-urun-sayfasi',
    name: 'E-Ticaret Ürün Sayfası',
    description: 'Ürün detay sayfası tasarımı ve açıklama metni oluşturma',
    module: ProjectType.WEBSITE,
    tags: ['e-ticaret', 'ürün sayfası', 'sepette', 'dönüşüm'],
    systemPrompt: 'E-ticaret ürün sayfası oluştur. Ürün açıklaması, özellikler tablosu, yorumlar ve CTA butonları ekle.',
    defaultParams: { framework: 'nextjs', includeReviews: true },
  },
  {
    id: 'crm-veri-tablosu',
    name: 'CRM Veri Tablosu',
    description: 'Müşteri ilişkileri yönetimi için veri tablosu ve analiz',
    module: ProjectType.SHEET,
    tags: ['CRM', 'müşteri', 'veri', 'analiz'],
    systemPrompt: 'CRM veri tablosu oluştur. Müşteri listesi, iletişim geçmişi, satış hunisi ve takip tablosu ekle.',
    defaultParams: { includePipeline: true, currency: 'TRY' },
  },
  {
    id: 'youtube-video-plan',
    name: 'YouTube Video Planlayıcı',
    description: 'YouTube video konsepti, senaryo ve thumbnail tasarımı',
    module: ProjectType.VIDEO,
    tags: ['youtube', 'video', 'senaryo', 'thumbnail'],
    systemPrompt: 'YouTube video planı oluştur. Video başlığı, açıklama, etiketler, senaryo ve thumbnail önerisi üret.',
    defaultParams: { duration: '10dk', platform: 'youtube' },
  },
  {
    id: 'email-kampanya',
    name: 'E-posta Kampanya Tasarımı',
    description: 'E-posta bültenleri ve pazarlama kampanyaları',
    module: ProjectType.DOCUMENT,
    tags: ['e-posta', 'kampanya', 'pazarlama', 'bülten'],
    systemPrompt: 'E-posta kampanya içerikleri oluştur. Konu satırı, gövde metni ve CTA butonu önerileri üret.',
    defaultParams: { type: 'newsletter', tone: 'friendly' },
  },
  {
    id: 'logo-konsept',
    name: 'Logo Konsept Oluşturucu',
    description: 'Marka kimliği için logo konseptleri ve varyasyonlar',
    module: ProjectType.IMAGE,
    tags: ['logo', 'marka', 'kimlik', 'tasarım'],
    systemPrompt: 'Logo konseptleri oluştur. Minimal, modern ve sektör uyumlu tasarımlar üret.',
    defaultParams: { ratio: '1:1', style: 'minimal', background: 'transparent' },
  },
  {
    id: 'mvc-web-uygulama',
    name: 'MVC Web Uygulama Şablonu',
    description: 'Model-View-Controller mimarisinde web uygulama iskeleti',
    module: ProjectType.WEBSITE,
    tags: ['MVC', 'web uygulama', 'şablon', 'full-stack'],
    systemPrompt: 'MVC mimarisinde web uygulama şablonu oluştur. Kullanıcı kimlik doğrulama, CRUD işlemleri ve dashboard ekle.',
    defaultParams: { framework: 'nextjs', includeAuth: true },
  },
  {
    id: 'anket-raporu',
    name: 'Anket ve Rapor Oluşturucu',
    description: 'Anket soruları, veri toplama ve analiz raporu',
    module: ProjectType.SHEET,
    tags: ['anket', 'veri toplama', 'rapor', 'istatistik'],
    systemPrompt: 'Anket soruları ve analiz raporu oluştur. Çoktan seçmeli sorular, grafikler ve istatistiksel özet ekle.',
    defaultParams: { questionCount: 15, includeCharts: true },
  },
  {
    id: 'sosyal-medya-strateji',
    name: 'Sosyal Medya Strateji Belgesi',
    description: 'Kapsamlı sosyal medya stratejisi ve içerik planı',
    module: ProjectType.DOCUMENT,
    tags: ['sosyal medya', 'strateji', 'içerik planı', 'pazarlama'],
    systemPrompt: 'Sosyal medya strateji belgesi oluştur. Hedef kitle analizi, platform stratejisi ve içerik takvimi ekle.',
    defaultParams: { platforms: ['instagram', 'twitter', 'linkedin'], duration: '1 ay' },
  },
];